#!/bin/bash -e
#
# Packages the src files into a .zip archive

npm run transpile

package_name="$(basename $(git rev-parse --show-toplevel)).zip"

if [[ "$OS" == "Windows_NT" ]]; then
    powershell "Compress-Archive src/* ${package_name}"
else
    zip -r -9 "${package_name}" src/*
fi

echo "Created ${package_name}"
